// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/MaisamV/wallet/internal/wallet"
	"github.com/MaisamV/wallet/internal/wallet/application/command"
	"github.com/MaisamV/wallet/internal/wallet/infrastructure/repo"
	"github.com/MaisamV/wallet/platform"
	"github.com/MaisamV/wallet/platform/config"
	"github.com/MaisamV/wallet/platform/logger"
)

// Injectors from wire.go:

// InitializeApplication creates and initializes the application with all dependencies
func InitializeApplication() (*Application, error) {
	config, err := platform.ProvideConfig()
	if err != nil {
		return nil, err
	}
	logger := platform.ProvideLogger(config)
	pool, err := platform.ProvideDatabase(config, logger)
	if err != nil {
		return nil, err
	}
	pgxWalletRepo := user.ProvideWalletRepository(logger, pool)
	releaseCommandHandler := user.ProvideReleaseCommandHandler(logger, pgxWalletRepo)
	walletModule := ProvideWalletModule(releaseCommandHandler, pgxWalletRepo)
	application := ProvideApplication(config, logger, walletModule)
	return application, nil
}

// wire.go:

// Application holds all the application dependencies
type Application struct {
	Config *config.Config
	Logger logger.Logger
	Wallet *WalletModule
}

type WalletModule struct {
	ReleaseHandler *command.ReleaseCommandHandler
	Repo           *infrastructure.PgxWalletRepo
}

// ProvideSwaggerModule provides the swagger module
func ProvideWalletModule(
	handler *command.ReleaseCommandHandler,
	repo *infrastructure.PgxWalletRepo,
) *WalletModule {
	return &WalletModule{
		ReleaseHandler: handler,
		Repo:           repo,
	}
}

// ProvideApplication provides the main application structure
func ProvideApplication(config2 *config.Config, logger2 logger.Logger,

	walletModule *WalletModule,
) *Application {
	return &Application{
		Config: config2,
		Logger: logger2,
		Wallet: walletModule,
	}
}
